version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/r3labs/broadcast
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make dev-deps
      - run: make test
